/* godouken_stencil_style_shared.h */

#ifndef GODOUKEN_STENCIL_STYLE_SHARED_H
#define GODOUKEN_STENCIL_STYLE_SHARED_H

#include <string>

static const std::string godouken_stencil_style_shared =
		"html,\n"
		"body {\n"
		"\tmin-width: 100%;\n"
		"\tmin-height: 100%;\n"
		"\tpadding: 0;\n"
		"\tmargin: 0;\n"
		"}\n"
		"\n"
		"a:link,\n"
		"a:visited {\n"
		"\tcolor: #FF8C00;\n"
		"\tfont-weight: bold;\n"
		"}\n"
		"\n"
		".text-orange {\n"
		"\tcolor: #FF8C00;\n"
		"}\n"
		"\n"
		".scroll-y {\n"
		"\toverflow-y: scroll;\n"
		"\toverflow-x: hidden;\n"
		"\tscrollbar-width: none\n"
		"}\n"
		"\n"
		"#sidebar {\n"
		"\tbackground-color: rgba(240, 240, 240, 200);\n"
		"}\n"
		"\n"
		"#sidebar-nav ul {\n"
		"\tlist-style-type: none;\n"
		"\tpadding: 0;\n"
		"}\n"
		"\n"
		"#logo-container {\n"
		"\tbackground: rgba(250, 250, 250, 200);\n"
		"}\n"
		"\n"
		".project-header {\n"
		"\tfont-size: 1.1vw;\n"
		"}\n"
		"\n"
		".tree-item:hover {\n"
		"\tbackground-color: rgba(235, 235, 235, 200);\n"
		"}\n"
		"\n"
		".tree-item a,\n"
		".tree-item a:hover {\n"
		"\tfont-weight: 700;\n"
		"\tfont-size: 0.8em;\n"
		"\tdisplay: block;\n"
		"\tpadding: 1px 0 1px 5%;\n"
		"\tcolor: #111;\n"
		"\ttext-decoration: none;\n"
		"}\n"
		"\n"
		".tree-item-heading {\n"
		"\tmargin-top: 5px;\n"
		"\tmargin-left: 5%;\n"
		"\tmargin-bottom: 5px;\n"
		"\tfont-weight: bold;\n"
		"\tcolor: #FF8C00;\n"
		"}\n"
		"\n"
		".no-wrap {\n"
		"\twhite-space: nowrap;\n"
		"}\n"
		"\n"
		".uppercase {\n"
		"\ttext-transform: uppercase;\n"
		"}\n"
		"\n"
		".text-sizing-1 {\n"
		"\tfont-size: 0.8em !important;\n"
		"}\n"
		"\n"
		".widget {\n"
		"\tpadding: 0.2rem 0.3rem;\n"
		"\tfont-size: 0.75rem;\n"
		"\tfont-weight: bold;\n"
		"}\n"
		"\n"
		"/* used in conjunction with the border class from bootstrap */\n"
		".border-2 { border-width: 2px !important; }\n"
		".border-3 {\tborder-width: 3px !important; }\n"
		"\n"
		"/* used with headers in script definition files to add style to headers */\n"
		".special-1 { letter-spacing: 3px; }\n"
		".special-2 { letter-spacing: 0.05rem; }\n"
		"\n"
		"/* used in displaying code snippets to add indentation */\n"
		".indent-0 { margin-left: 0px; }\n"
		".indent-1 { margin-left: 16px; }\n"
		".indent-2 { margin-left: 32px; }\n"
		".indent-3 { margin-left: 48px; }\n"
		".indent-4 { margin-left: 64px; }\n"
		".indent-5 { margin-left: 80px; }\n"
		".indent-6 { margin-left: 96px; }\n"
		".indent-7 { margin-left: 112px; }\n"
		".indent-8 { margin-left: 128px; }\n"
		".indent-9 { margin-left: 144px; }\n"
		"\n"
		"::-webkit-scrollbar {\n"
		"    width: 0px;  /* Remove scrollbar space */\n"
		"    background: transparent;  /* Optional: just make scrollbar invisible */\n"
		"}\n"
		"\n"
		".table td.fit,\n"
		".table th.fit {\n"
		"    white-space: nowrap;\n"
		"    width: 1%;\n"
		"}\n"
		"\n"
		".demo-icon\n"
		"{\n"
		"\tfont-family: \"fontello\";\n"
		"\tfont-style: normal;\n"
		"\tfont-weight: normal;\n"
		"\tspeak: none;\n"
		"\tdisplay: inline-block;\n"
		"\ttext-decoration: inherit;\n"
		"\twidth: 1em;\n"
		"\tmargin-right: .2em;\n"
		"\ttext-align: center;\n"
		"\tfont-variant: normal;\n"
		"  \ttext-transform: none;\n"
		" \tline-height: 1em;\n"
		"\tmargin-left: .2em;\n"
		"\t-webkit-font-smoothing: antialiased;\n"
		"  \t-moz-osx-font-smoothing: grayscale;\n"
		"}";

#endif // GODOUKEN_STENCIL_STYLE_SHARED_H
