/* godouken_stencil_class.h */

#ifndef GODOUKEN_STENCIL_CLASS_H
#define GODOUKEN_STENCIL_CLASS_H

#include <string>

static const std::string godouken_stencil_class =
		"<html>\n"
		"\t<head>\n"
		"\t\t<title>{{ data.project_title }} /// {{ data.script.name }}</title>\n"
		"\t\t<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\" integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\" crossorigin=\"anonymous\">\n"
		"        <link rel=\"stylesheet\" href=\"./../css/style_shared.css\">\n"
		"        <link rel=\"stylesheet\" href=\"./../css/style_class.css\">\n"
		"\t</head>\n"
		"\t<body>\n"
		"\t\t<div class=\"container-fluid h-100\" id=\"main-content\">\n"
		"\t\t\t<div class=\"row h-100\">\n"
		"\t\t\t\t<div class=\"col-2 h-100 d-flex flex-column p-0\" id=\"sidebar\">\n"
		"\t\t\t\t\t<div id=\"logo-container\" class=\"container-fluid p-1\">\n"
		"\t\t\t\t\t\t<div class=\"mb-2\">\n"
		"\t\t\t\t\t\t\t<!--<a href=\"script_humanoid.html\">\n"
		"\t\t\t\t\t\t\t\t<img class=\"img img-rounded bounceIn\" src=\"document-icon.png\" width=\"100%\">\n"
		"\t\t\t\t\t\t\t</a>-->\n"
		"\t\t\t\t\t\t\t<div class=\"mt-3 text-center\">\n"
		"\t\t\t\t\t\t\t\t<strong class=\"project-header border-bottom\">{{ data.project_title }}</strong>\n"
		"\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t</div>\n"
		"\t\t\t\t\t<div id=\"sidebar-nav\" class=\"container-fluid p-0 scroll-y\">\n"
		"\t\t\t\t\t\t<ul>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item-heading\">OVERVIEW</li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Introduction</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Project Graph</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">About</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Todos</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Roadmaps</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item-heading\">COLLECTIONS</li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Entities</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Levels</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Systems</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Menus</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item-heading\">SCRIPT API</li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">DefaultWeapon</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Enemy</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">EnemyState</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Humanoid</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">InfantryPilot</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Kitten</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">LevelUI</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">MainMenu</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">ManagerGame</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">ManagerLevel</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Player</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">PlayerKeystate</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">PlayerKeystateSorter</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">StatWidget</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">Upgrade</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">UpgradeProjectile</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">UpgradeSocket</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">UpgradeStats</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">UpgradeSystem</a></li>\n"
		"\t\t\t\t\t\t\t<li class=\"tree-item\"><a href=\"#\">UpgradeType</a></li>\n"
		"\t\t\t\t\t\t</ul>\n"
		"\t\t\t\t\t</div>\n"
		"\t\t\t\t</div>\n"
		"\t\t\t\t<div class=\"col-10 h-100 d-flex flex-column scroll-y\">\n"
		"\t\t\t\t\t<div class=\"my-3\">\n"
		"\t\t\t\t\t\t<nav aria-label=\"breadcrumb\">\n"
		"\t\t\t\t\t\t\t<ol class=\"breadcrumb\">\n"
		"\t\t\t\t\t\t\t\t{% for crumb in data.script.breadcrumbs %}\n"
		"                                <li class=\"breadcrumb-item\"><a href=\"#\">{{ crumb }}</a></li>\n"
		"                                {% endfor %}\n"
		"\t\t\t\t\t\t\t</ol>\n"
		"\t\t\t\t\t\t</nav>\n"
		"\t\t\t\t\t\t<div id=\"content-script-tree\" class=\"container mt-5 text-center\">\n"
		"\t\t\t\t\t\t\t<div class=\"alert alert-secondary\" role=\"alert\">\n"
		"\t\t\t\t\t\t\t\t<strong>Script Inheritance Tree</strong>\n"
		"\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t<div id=\"content-title\" class=\"container\">\n"
		"\t\t\t\t\t\t\t<div class=\"row justify-content-center\">\n"
		"\t\t\t\t\t\t\t\t<h2 class=\"my-0 bounceIn\"><strong>{{ data.script.name }}</strong></h2>\n"
		"\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t\t<div class=\"row justify-content-center mt-3\">\n"
		"                                {% if data.script.meta.deprecated %}\n"
		"\t\t\t\t\t\t\t\t<div class=\"ml-2 d-flex text-white\">\n"
		"\t\t\t\t\t\t\t\t\t<div class=\"widget bg-danger rounded-left mx-0\">deprecated</div>\n"
		"\t\t\t\t\t\t\t\t\t<div class=\"widget bg-dark rounded-right mx-0\">{{ data.script.meta.deprecated }}</div>\n"
		"\t\t\t\t\t\t\t\t</div>\n"
		"                                {% endif %}\n"
		"                                {% if data.script.meta.version %}\n"
		"\t\t\t\t\t\t\t\t<div class=\"ml-2 d-flex text-white\">\n"
		"\t\t\t\t\t\t\t\t\t<span class=\"widget bg-info rounded-left mx-0\">version</span>\n"
		"\t\t\t\t\t\t\t\t\t<span class=\"widget bg-dark rounded-right mx-0\">{{ data.script.meta.version }}</span>\n"
		"\t\t\t\t\t\t\t\t</div>\n"
		"                                {% endif %}\n"
		"                                {% if data.script.meta.created %}\n"
		"\t\t\t\t\t\t\t\t<div class=\"ml-2 d-flex text-white\">\n"
		"\t\t\t\t\t\t\t\t\t<span class=\"widget bg-success rounded-left mx-0\">created</span>\n"
		"\t\t\t\t\t\t\t\t\t<span class=\"widget bg-dark rounded-right mx-0\">{{ data.script.meta.created }}</span>\n"
		"\t\t\t\t\t\t\t\t</div>\n"
		"                                {% endif %}\n"
		"                                {% if data.script.meta.modified %}\n"
		"\t\t\t\t\t\t\t\t<div class=\"ml-2 d-flex text-white\">\n"
		"\t\t\t\t\t\t\t\t\t<span class=\"widget bg-success rounded-left mx-0\">last modified</span>\n"
		"\t\t\t\t\t\t\t\t\t<span class=\"widget bg-dark rounded-right mx-0\">{{ data.script.meta.modified }}</span>\n"
		"\t\t\t\t\t\t\t\t</div>\n"
		"                                {% endif %}\n"
		"                                {% if data.script.meta.collection %}\n"
		"\t\t\t\t\t\t\t\t<div class=\"ml-2 d-flex text-white\">\n"
		"\t\t\t\t\t\t\t\t\t<span class=\"widget bg-warning rounded-left mx-0\">collection</span>\n"
		"\t\t\t\t\t\t\t\t\t<span class=\"widget bg-dark rounded-right mx-0\">{{ data.script.meta.collection }}</span>\n"
		"\t\t\t\t\t\t\t\t</div>\n"
		"                                {% endif %}\n"
		"\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t\t<div class=\"description\">\n"
		"\t\t\t\t\t\t\t\t<div class=\"row mt-4\">\n"
		"\t\t\t\t\t\t\t\t\t<h3 class=\"special-1\">Brief Description</h3>\n"
		"\t\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t\t\t<div class=\"row border-left border-info border-3 px-2 mt-2\">\n"
		"\t\t\t\t\t\t\t\t\t<i>{{ data.script.description.brief }}</i>\n"
		"\t\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t\t<div class=\"description\">\n"
		"\t\t\t\t\t\t\t\t<div class=\"row mt-4\">\n"
		"\t\t\t\t\t\t\t\t\t<h3 class=\"special-1\">Detailed Description</h3>\n"
		"\t\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t\t\t<div class=\"row border-left border-info border-3 px-2 mt-2\">\n"
		"\t\t\t\t\t\t\t\t\t<i>{{ data.script.description.detailed }}</i>\n"
		"\t\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t<div id=\"content-main-body\" class=\"container my-3\">\n"
		"\t\t\t\t\t\t\t<div class=\"row\">\n"
		"\t\t\t\t\t\t\t\t<h5 class=\"special-1\">Script Properties</h5>\n"
		"\t\t\t\t\t\t\t\t<table class=\"table table-sm mt-3\">\n"
		"\t\t\t\t\t\t\t\t\t<thead>\n"
		"\t\t\t\t\t\t\t\t\t\t<tr>\n"
		"\t\t\t\t\t\t\t\t\t\t\t<td><strong>Property Type</strong></td>\n"
		"\t\t\t\t\t\t\t\t\t\t\t<td><strong>Property Name</strong></td>\n"
		"\t\t\t\t\t\t\t\t\t\t\t<td><strong>Special Tags</strong></td>\n"
		"\t\t\t\t\t\t\t\t\t\t</tr>\n"
		"\t\t\t\t\t\t\t\t\t</thead>\n"
		"\t\t\t\t\t\t\t\t\t<tbody>\n"
		"                                        {% for property in data.script.properties %}\n"
		"                                        <tr>\n"
		"                                            <td>{% if property.type_info.href %}<a href=\"{{ property.type_info.href }}\" target=\"_blank\">{{ property.type_info.name }}</a>{% else %}{{ property.type_info.name }}{% endif %}</td>\n"
		"                                            <td><a href=\"#{{ property.name }}\">{{ property.name }}</a></td>\n"
		"                                                {% if property.tags %}\n"
		"                                                <td>\n"
		"                                                {% if property.tags.is_godot %}\n"
		"                                                <div class=\"d-flex text-white\">\n"
		"                                                    <span class=\"widget bg-dark rounded mx-0 px-2\">godot type</span>\n"
		"                                                </div>\n"
		"                                                {% endif %}\n"
		"                                                {% if property.tags.is_exported %}\n"
		"                                                <div class=\"d-flex text-white\">\n"
		"                                                    <span class=\"widget bg-dark rounded mx-0 px-2\">exports // {{ property.type_info.name }}</span>\n"
		"                                                </div>\n"
		"                                                {% endif %}\n"
		"                                            </td>\n"
		"                                            {% endif %}\n"
		"                                        </tr>\n"
		"                                        {% endfor %}\n"
		"\t\t\t\t\t\t\t\t\t</tbody>\n"
		"\t\t\t\t\t\t\t\t</table>\n"
		"\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t<div id=\"content-main-body-detailed\" class=\"container my-3\">\n"
		"\t\t\t\t\t\t\t<div class=\"row mt-3\">\n"
		"\t\t\t\t\t\t\t\t<h3 class=\"special-1\">Property Descriptions</h3>\n"
		"\t\t\t\t\t\t\t\t<div class=\"method-descriptor container-fluid border-left border-success border-3 bg-light mt-3\">\n"
		"                                    {% for property in data.script.properties %}\n"
		"                                    <div class=\"container-fluid border-left border-info border-3 my-3 ml-2 py-2\">\n"
		"                                        <div class=\"row ml-2 mt-2 d-flex flex-column\">\n"
		"                                            <span class=\"special-2\"><i><strong>Property Signature</strong></i></span>\n"
		"                                            <div>\n"
		"                                                <h6 class=\"my-0\">\n"
		"                                                    {% if property.type_info.href %}\n"
		"                                                    <a href=\"{{ property.type_info.href }}\" target=\"_blank\">{{ property.type_info.name }}</a>\n"
		"                                                    {% else %}\n"
		"                                                    {{ property.type_info.name }}\n"
		"                                                    {% endif %}\n"
		"                                                    {{ property.name }}\n"
		"                                                </h6>\n"
		"                                                {% if property.description.detailed %}\n"
		"                                                <p>{{ property.description.detailed }}</p>\n"
		"                                                {% endif %}\n"
		"                                                <p></p>\n"
		"                                            </div>\n"
		"                                        </div>\n"
		"                                    </div>\n"
		"                                    {% endfor %}\n"
		"\t\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t\t</div>\n"
		"\t\t\t\t\t</div>\n"
		"\t\t\t\t</div>\n"
		"\t\t\t</div>\n"
		"\t\t</div>\n"
		"\t\t<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\n"
		"        <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\n"
		"        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js\" integrity=\"sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF\" crossorigin=\"anonymous\"></script>\n"
		"\t</body>\n"
		"</html>";

#endif GODOUKEN_STENCIL_CLASS_H // GODOUKEN_STENCIL_CLASS_H
