start python script_conversion.py html/script_template_class .html godouken_stencil_class
start python script_conversion.py html/script_template_class_sidebar .html godouken_stencil_class_sidebar
start python script_conversion.py html/script_template_directories .html godouken_stencil_directory
start python script_conversion.py css/template_main .css godouken_stencil_style